# This is just a dummy config and should be replaced by mounting!
llm_response_generation:
  type: "openai-api"
  model: "gpt-oss-120b"
  api_url: https://llm.ai.e-infra.cz/v1/
  api_key: "xxx"
  workers: 4

dsw:
  api_url: ""

auth:
  allowed_project_urls:
    - "https://your-dsw-instance.example.com"

logging:
  level: "INFO"

database:
  host: "localhost"
  port: "5432"
  name: "ai_document_plugin"
  user: "ai_document_plugin"
  password: "ai_document_plugin"
  schema: "public"

files:
  prompts_path: "./prompts.yaml"
